name: PHP Runner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      run: git clone https://github.com/zigou23/bing-wallpaper wp
    - name: Run PHP
      run: cd wp && sudo apt update && sudo apt install php7.4 -y && php7.4 ./json/generate15day.php

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./*.json
    - name: Commit files
      run: |
         git config --local user.email "a1923458037@gmail.com"
         git config --local user.name "zigou23"
         git add .
         git commit -m "update"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
